import "./globals.css";
import Navbar from "./pages/header/page";

export const metadata = {
  title: "New Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-serif">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
